version: "3.2"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules:/alertmanager/alert.rules
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
  alertmanager:
    image: prom/alertmanager
    privileged: true
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager.yml
    command:
      - "--config.file=/alertmanager.yml"
    ports:
      - "9093:9093"
