global:
  scrape_interval: 5s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["node_exporter:9100"]
rule_files:
  - "/alertmanager/alert.rules"
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
